using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace LPL.Gatekeeper.Models;

// ─── Audit Event Document ─────────────────────────────────────
// This is how an audit event is stored in MongoDB.
// Each document in the audit_events collection matches this shape.
//
// MongoDB vs SQL mental model:
// Collection = Table
// Document   = Row
// Field      = Column
// _id        = Primary Key (auto-generated by MongoDB)
//
// Key difference: documents in the same collection CAN have
// different fields. If we add a new field next month, old
// documents simply won't have it — no migration needed.
// ─── Session Document ─────────────────────────────────────────
// Replaces the in-memory conversation_store in Python FastAPI.
// Day 5 moves session storage to MongoDB so sessions survive
// server restarts and work across multiple Python instances.
public class SessionDocument
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string? Id { get; set; }

    [BsonElement("sessionId")]
    public string SessionId { get; set; } = "";

    [BsonElement("userId")]
    public string UserId { get; set; } = "";

    [BsonElement("department")]
    public string Department { get; set; } = "";

    // History is embedded as an array of sub-documents.
    // In SQL this would be a separate table with a foreign key.
    // In MongoDB we embed it — one document = one session + history.
    // This is the embedding pattern vs referencing pattern.
    [BsonElement("history")]
    public List<SessionMessage> History { get; set; } = new();

    [BsonElement("createdAt")]
    [BsonDateTimeOptions(Kind = DateTimeKind.Utc)]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [BsonElement("lastUsedAt")]
    [BsonDateTimeOptions(Kind = DateTimeKind.Utc)]
    public DateTime LastUsedAt { get; set; } = DateTime.UtcNow;

    // TTL field — MongoDB will automatically delete this document
    // after ExpiresAt passes. Configured by an index.
    [BsonElement("expiresAt")]
    [BsonDateTimeOptions(Kind = DateTimeKind.Utc)]
    public DateTime ExpiresAt { get; set; } =
        DateTime.UtcNow.AddHours(8);
}

public class SessionMessage
{
    [BsonElement("role")]
    public string Role { get; set; } = "";    // "user" or "assistant"

    [BsonElement("content")]
    public string Content { get; set; } = "";

    [BsonElement("sources")]
    public List<string> Sources { get; set; } = new();

    [BsonElement("timestamp")]
    [BsonDateTimeOptions(Kind = DateTimeKind.Utc)]
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
}
